version: '3.8'

services:
  postgres:
    image: postgres
    container_name: my-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: LinkShrinkerAuth
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
